# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.cache/wt [current_project]
set_property parent.project_path C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_mem {
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/Complete_Demo_ROM.txt
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/Complete_Demo_RAM.txt
}
read_verilog -library xil_defaultlib {
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/MouseNew/MouseTransmitter.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/MouseNew/MouseReceiver.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/MouseNew/MouseMasterSM.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/MouseNew/MouseTransceiver.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/ALU.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/MouseNew/seg7decoder.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/7Seg_Peripheral.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/Processor.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/Time.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/ROM.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/LED_.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/RAM.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/MouseNew/Top.v
  C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/sources_1/imports/Mouse_Proceesor_W8test/SystemTop.v
}
read_xdc C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/constrs_1/imports/MouseNew/Mouse_homelapXDC.xdc
set_property used_in_implementation false [get_files C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.srcs/constrs_1/imports/MouseNew/Mouse_homelapXDC.xdc]

synth_design -top SystemTop -part xc7a35tcpg236-1
write_checkpoint -noxdef SystemTop.dcp
catch { report_utilization -file SystemTop_utilization_synth.rpt -pb SystemTop_utilization_synth.pb }
