webtalk_init -webtalk_dir C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Mar 07 00:30:16 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1266856" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "213171080_0_0_320" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "091027c1-eb50-49a8-a2ee-c037443e9018" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0caf23fa-aea6-400a-a824-48fa9aa836ef" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-14900HX" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Digilent/Basys3/15000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0362D093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 1074048605 -regid "213171080_0_0_320" -xml C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.hw/webtalk/usage_statistics_ext_labtool.xml -html C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.hw/webtalk/usage_statistics_ext_labtool.html -wdm C:/Users/Louis/Desktop/UoE/Fourth_Year/Mouse_Proceesor_W8test/Mouse_Proceesor_W8test.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
