`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company:
// Engineer:
//
// Create Date: 01.02.2026 13:13:21
// Design Name:
// Module Name: MouseTransceiver
// Project Name:
// Target Devices:
// Tool Versions:
// Description: See below.
//
// Dependencies:
//
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
//
//////////////////////////////////////////////////////////////////////////////////

/*
PS/2 Host-to-Device Transmitter

This module implements host-initiated PS/2 communication,
where the FPGA acts as the bus master and the mouse is the bus slave.

Transmission procedure (PS/2 protocol):
//   1) Host pulls CLK line low for at least 100 us to request
//      transmission.
//   2) Host pulls DATA low (start bit) and releases CLK.
//   3) Device generates the clock.
//   4) Host drives:
//        - 8 data bits (LSB first)
//        - odd parity bit
//        - stop bit (1)
//   5) Device acknowledges by pulling DATA low, then CLK low.
//   6) Host waits until both lines are released.
//

Data is sampled by the device on rising clock edges, therefore the host updates DATA on falling edges.
*/

module MouseTransmitter(
	//Standard Inputs
    input RESET,				// Synchronous reset
	input CLK,                  // System clock (100 MHz)

    //Mouse IO - CLK
    input  CLK_MOUSE_IN,		// Clock generated by mouse
    output CLK_MOUSE_OUT_EN,	// Pull clock low when asserted

    //Mouse IO - DATA
    input  DATA_MOUSE_IN,		// Data from mouse
    output DATA_MOUSE_OUT,		// Data driven by host
    output DATA_MOUSE_OUT_EN,	// Enable host driving DATA

    // Control
    input        SEND_BYTE,		// Request to send one byte
    input  [7:0] BYTE_TO_SEND,	// Byte to transmit
    output       BYTE_SENT		// Asserted when transmission completes
);

    // Delayed version of PS/2 clock used to detect falling edges.
	// Falling edge: previous = 1, current = 0.
    reg ClkMouseInDly;
    always @(posedge CLK)
        ClkMouseInDly <= CLK_MOUSE_IN;

    // FSM registers
    // Curr_State holds the current transmission state
    // Next_State is computed combinationally
    reg [3:0] Curr_State, Next_State;
    reg Curr_MouseClkOutWE, Next_MouseClkOutWE;
    reg Curr_MouseDataOut, Next_MouseDataOut;
    reg Curr_MouseDataOutWE, Next_MouseDataOutWE;
    reg [15:0] Curr_SendCounter, Next_SendCounter;
    reg Curr_ByteSent, Next_ByteSent;
    reg [7:0] Curr_ByteToSend, Next_ByteToSend;

    // Sequential
    always @(posedge CLK) begin
        if (RESET) begin
            Curr_State <= 0;
            Curr_MouseClkOutWE <= 0;
            Curr_MouseDataOut <= 0;
            Curr_MouseDataOutWE <= 0;
            Curr_SendCounter <= 0;
            Curr_ByteSent <= 0;
            Curr_ByteToSend <= 0;
        end else begin
            Curr_State <= Next_State;
            Curr_MouseClkOutWE <= Next_MouseClkOutWE;
            Curr_MouseDataOut <= Next_MouseDataOut;
            Curr_MouseDataOutWE <= Next_MouseDataOutWE;
            Curr_SendCounter <= Next_SendCounter;
            Curr_ByteSent <= Next_ByteSent;
            Curr_ByteToSend <= Next_ByteToSend;
        end
    end

    // Combinational FSM
    always @* begin
        Next_State = Curr_State;
        Next_MouseClkOutWE = 0;
        Next_MouseDataOut = 0;
        Next_MouseDataOutWE = Curr_MouseDataOutWE;
        Next_SendCounter = Curr_SendCounter;
        Next_ByteSent = 0;
        Next_ByteToSend = Curr_ByteToSend;

        case(Curr_State)
            // IDLE
            4'h0: begin
                Next_MouseDataOutWE = 0;
                if (SEND_BYTE) begin
                    Next_State = 4'h1;
                    Next_ByteToSend = BYTE_TO_SEND;
                end
            end

            // State 1:
			// Host pulls CLK low for more than 100 us to request transmission.
            4'h1: begin
                Next_MouseClkOutWE = 1;
                if (Curr_SendCounter == 6000) begin
                    Next_State = 4'h2;
                    Next_SendCounter = 0;
                end else
                    Next_SendCounter = Curr_SendCounter + 1;
            end

            // Pull data low, release clock
            4'h2: begin
                Next_MouseDataOutWE = 1;
                Next_State = 4'h3;
            end

            // Start bit
            4'h3: begin
                if (ClkMouseInDly && ~CLK_MOUSE_IN)
                    Next_State = 4'h4;
            end

            // Send 8 data bits, LSB first.
            4'h4: begin
                if (ClkMouseInDly && ~CLK_MOUSE_IN) begin
                    if (Curr_SendCounter == 7) begin
                        Next_State = 4'h5;
                        Next_SendCounter = 0;
                    end else
                        Next_SendCounter = Curr_SendCounter + 1;
                end
                Next_MouseDataOut = Curr_ByteToSend[Curr_SendCounter];
            end

            // Parity
            4'h5: begin
                if (ClkMouseInDly && ~CLK_MOUSE_IN)
                    Next_State = 4'h6;
                Next_MouseDataOut = ~^Curr_ByteToSend;
            end

            // Stop bit
            // Stop bit must be logic '1'.
            4'h6: begin
                if (ClkMouseInDly && ~CLK_MOUSE_IN)
                    Next_State = 4'h7;
                Next_MouseDataOut = 1;
            end

            // Release data
            4'h7: begin
                Next_MouseDataOutWE = 0;
                Next_State = 4'h8;
            end

            // Wait for device acknowledgement sequence:
			//   1) Device pulls DATA low
			//   2) Device pulls CLK low
			//   3) Device releases both lines
            4'h8: if (~DATA_MOUSE_IN) Next_State = 4'h9;
            
            4'h9: if (~CLK_MOUSE_IN)  Next_State = 4'hA;

            4'hA: begin
                if (DATA_MOUSE_IN && CLK_MOUSE_IN) begin
                    Next_State = 4'h0;
                    Next_ByteSent = 1;
                end
            end
        endcase
    end

    assign CLK_MOUSE_OUT_EN  = Curr_MouseClkOutWE;
    assign DATA_MOUSE_OUT    = Curr_MouseDataOut;
    assign DATA_MOUSE_OUT_EN = Curr_MouseDataOutWE;
    assign BYTE_SENT         = Curr_ByteSent;

endmodule
